name: gsoc
channels:
  - conda-forge
  - rdkit
  - ambermd
dependencies:
  # Base
  - python=3.8
  - ipython
  - pip

  # Science
  - numpy
  - scipy
  - pandas
  - scikit-learn
  
  - biopython
  - prody

  - rdkit
  - openbabel
  - MDAnalysis

  - qcelemental

  - networkx
  - graph-tool

  # Plotting
  - matplotlib
  - seaborn

  # Misc
  - tqdm

  # Devtools
  - black
  - cython
  - pytest
  - setuptools
