name: gsoc
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.3
  - appdirs=1.4.4
  - attrs=21.2.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bcrypt=3.2.0
  - biopython=1.79
  - black=21.7b0
  - boost=1.74.0
  - boost-cpp=1.74.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2021.5.30
  - cairo=1.16.0
  - certifi=2021.5.30
  - cffi=1.14.6
  - chardet=4.0.0
  - charset-normalizer=2.0.0
  - click=8.0.1
  - cryptography=3.4.7
  - curl=7.71.1
  - cycler=0.10.0
  - cython=0.29.24
  - dataclasses=0.8
  - dbus=1.13.6
  - expat=2.4.1
  - flake8=3.9.2
  - fontconfig=2.13.1
  - freetype=2.10.4
  - gettext=0.19.8.1
  - glib=2.68.3
  - glib-tools=2.68.3
  - greenlet=1.1.0
  - griddataformats=0.5.0
  - gsd=2.4.2
  - gst-plugins-base=1.18.4
  - gstreamer=1.18.4
  - hdf4=4.2.15
  - hdf5=1.10.1
  - icu=68.1
  - idna=3.1
  - importlib-metadata=4.6.1
  - importlib_metadata=4.6.1
  - importlib_resources=5.2.0
  - iniconfig=1.1.1
  - ipykernel=5.3.4
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - isort=5.9.3
  - jbig=2.1
  - jedi=0.17.2
  - joblib=1.0.1
  - jpeg=9d
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - kiwisolver=1.3.1
  - krb5=1.19.1
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=2.2.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcurl=7.71.1
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libevent=2.1.10
  - libffi=3.3
  - libgcc-ng=11.1.0
  - libgfortran=3.0.0
  - libgfortran-ng=11.1.0
  - libgfortran5=11.1.0
  - libglib=2.68.3
  - libgomp=11.1.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libnetcdf=4.4.1.1
  - libogg=1.3.4
  - libopenblas=0.3.15
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=13.3
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=11.1.0
  - libtiff=4.3.0
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp-base=1.2.0
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mccabe=0.6.1
  - more-itertools=8.8.0
  - msgpack-python=1.0.2
  - mypy=0.910
  - mypy_extensions=0.4.3
  - mysql-common=8.0.25
  - mysql-libs=8.0.25
  - ncurses=6.2
  - netcdf4=1.3.1
  - nspr=4.30
  - nss=3.67
  - numpy=1.19.5
  - olefile=0.46
  - openbabel=3.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - packaging=21.0
  - pandas=1.1.5
  - paramiko=2.7.2
  - parso=0.7.1
  - pathspec=0.9.0
  - patsy=0.5.1
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.3.1
  - pint=0.17
  - pip=21.2.1
  - pixman=0.40.0
  - pluggy=0.13.1
  - plumbum=1.7.0
  - prody=2.0
  - prompt-toolkit=3.0.19
  - psutil=5.8.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - py=1.10.0
  - pycairo=1.20.1
  - pycodestyle=2.7.0
  - pycparser=2.20
  - pydantic=1.8.2
  - pyflakes=2.3.1
  - pygments=2.9.0
  - pynacl=1.4.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pysocks=1.7.1
  - pytest=6.2.4
  - python=3.6.13
  - python-dateutil=2.8.2
  - python_abi=3.6
  - pytz=2021.1
  - pyzmq=20.0.0
  - qcelemental=0.21.0
  - qt=5.12.9
  - rdkit=2021.03.4
  - readline=8.1
  - regex=2021.7.6
  - reportlab=3.5.68
  - requests=2.26.0
  - scikit-learn=0.24.2
  - scipy=1.5.3
  - seaborn=0.11.1
  - seaborn-base=0.11.1
  - setuptools=49.6.0
  - six=1.16.0
  - spyrmsd=0.5.0
  - sqlalchemy=1.4.22
  - sqlite=3.36.0
  - statsmodels=0.12.2
  - threadpoolctl=2.2.0
  - tk=8.6.10
  - toml=0.10.2
  - tomli=1.1.0
  - tornado=6.1
  - tqdm=4.61.2
  - traitlets=4.3.3
  - typed-ast=1.4.3
  - typing-extensions=3.10.0.0
  - typing_extensions=3.10.0.0
  - urllib3=1.26.6
  - wcwidth=0.2.5
  - wheel=0.36.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.5.0
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - decorator==4.4.2
    - mdanalysis==2.0.0b0
    - mmtf-python==1.1.2
    - mpire==2.2.1
    - networkx==2.5.1
