#!/bin/bash

#$ -V
#$ -cwd
#$ -q parallel-biggin
#$ -pe parallel 8
#$ -N docking
#$ -o jobs/docking.out
#$ -e jobs/docking.err
#$ -t 1-158
#$ -tc 12

. /etc/profile.d/modules.sh

module load compilers/gcc/6.2.0

source variables/paths
source variables/docking

let index=$(( ${SGE_TASK_ID} - 1 ))

printf -v splitfile "split%03d" ${index}

echo $splitfile

for path in $(cat splits/${splitfile})
do
    
    dir=${pdbbind}/${path}
    system=$(basename ${dir})
    dataset=$(basename $(dirname ${dir}))

    # Docking working directory
    ddir=${dataset}/${system}
    mkdir -p ${ddir}
    mkdir -p ${ddir}/logs

    echo "Docking WD: ${ddir}"

    # Ligand and receptor
    ligand=${dir}/${system}_ligand.mol2
    receptor=${dir}/${system}_protein.pdb

    echo "Ligand: ${ligand}"
    echo "Receptor: ${receptor}"

    # Docking parameters
    source variables/docking

    # Print docking parameters
    echo "--flexdist_ligand ${ligand}"
    echo "--flexdist ${flexdist}"
    echo "--autobox_ligand ${ligand}"
    echo "--autobox_add ${autobox_add}"
    echo "--exhaustiveness ${exhaustiveness}"
    echo "--num_modes ${num_modes}"
    echo "--cpu 8"
    echo "--seed ${seed}"
	
    # Run docking
    ${smina} -r ${receptor} -l ${ligand} \
        --flexdist_ligand ${ligand} --flexdist 3 \
	--autobox_ligand ${ligand} --autobox_add ${autobox_add} \
	--exhaustiveness ${exhaustiveness} --num_modes ${num_modes} --cpu 8 \
        --out ${ddir}/dock.pdb --out_flex ${ddir}/flex.pdb \
        2>&1 | tee ${ddir}/logs/smina.log

done